// <auto-generated />
namespace Day3EF_Codefirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class new_property_in_car : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_property_in_car));
        
        string IMigrationMetadata.Id
        {
            get { return "202302101001142_new_property_in_car"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
